server.port=1005
server.max-http-header-size = 400000 

app.upload.dir=C:/stocksense/uploads

#oracle
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=mbc
spring.datasource.password=1234
spring.servlet.multipart.maxFileSize=10MB
spring.servlet.multipart.maxRequestSize=10MB

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# security
spring.security.user.name=user
spring.security.user.password=1234

## jpa #####################################################
#??? warnning ??
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#??? ??? sql ???
spring.jpa.show-sql=true
#sql ?? ?? ??
spring.jpa.properties.hibernate.format_sql=true
#sql ?? ?? ??
#logging.level.org.hibernate.SQL = debug #?? log? ?????
#logging.level.org.hibernate.orm.jdbc.bind=trace
#????? create ?? update ????? validate
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=oracle
#############################################################